In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics
from scipy.spatial.distance import cdist
from sklearn import preprocessing as prep

ModuleNotFoundError: No module named 'sklearn'

In [14]:
X = pd.read_excel('../Data/winequality-red.xlsx')

In [15]:
X.shape

(1600, 12)

In [18]:
X.sample(10)

,winequality-red,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
1185,6.7,0.64,0.23,2.1,0.08,11,119,0.99538,3.36,0.7,10.9,5
332,10.2,0.36,0.64,2.9,0.122,10,41,0.998,3.23,0.66,12.5,6
1322,5,0.74,0,1.2,0.041,16,46,0.99258,4.01,0.59,12.5,6
823,6.7,0.54,0.13,2,0.076,15,36,0.9973,3.61,0.64,9.8,5
501,7.8,0.52,0.25,1.9,0.081,14,38,0.9984,3.43,0.65,9,6
858,8.2,0.26,0.34,2.5,0.073,16,47,0.99594,3.4,0.78,11.3,7
232,8,0.38,0.06,1.8,0.078,12,49,0.99625,3.37,0.52,9.9,6
90,7,0.62,0.08,1.8,0.076,8,24,0.9978,3.48,0.53,9,5
137,8.3,0.715,0.15,1.8,0.089,10,52,0.9968,3.23,0.77,9.5,5
1204,9.9,0.74,0.19,5.8,0.111,33,76,0.99878,3.14,0.55,9.4,5

In [22]:
X.head()

,winequality-red,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1,7.4,0.7,0,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5
2,7.8,0.88,0,2.6,0.098,25,67,0.9968,3.2,0.68,9.8,5
3,7.8,0.76,0.04,2.3,0.092,15,54,0.997,3.26,0.65,9.8,5
4,11.2,0.28,0.56,1.9,0.075,17,60,0.998,3.16,0.58,9.8,6